"""Adiciona sistema de afiliados e configuracoes

Revision ID: 08a9ea3e07c4
Revises: 8795a348eabe
Create Date: 2025-11-07 15:36:20.634038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a9ea3e07c4'
down_revision: Union[str, Sequence[str], None] = '8795a348eabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('afiliado_ativo', sa.Boolean(), nullable=False),
    sa.Column('afiliado_gatilho', sa.Enum('primeira_recarga', 'primeira_compra', name='tipogatilhoafiliado'), nullable=False),
    sa.Column('afiliado_tipo_premio', sa.Enum('cashback_pendente', 'giftcard_imediato', name='tipopremioafiliado'), nullable=False),
    sa.Column('afiliado_valor_premio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('referrer_id', sa.Uuid(), nullable=True))
    op.add_column('usuario', sa.Column('pending_cashback_percent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'usuario', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'pending_cashback_percent')
    op.drop_column('usuario', 'referrer_id')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
