"""torna_pedido_estoque_id_opcional

Revision ID: 23892b69acd1
Revises: eb4a1913898b
Create Date: 2025-11-03 17:33:42.011366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23892b69acd1'
down_revision: Union[str, Sequence[str], None] = 'eb4a1913898b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('email_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('pedido', 'estoque_conta_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_pedido_email_cliente'), 'pedido', ['email_cliente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_email_cliente'), table_name='pedido')
    op.alter_column('pedido', 'estoque_conta_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pedido', 'email_cliente')
    # ### end Alembic commands ###
