"""adiciona bonus_cashback_percent na recargasaldo

Revision ID: 4475c1ce824d
Revises: 08a9ea3e07c4
Create Date: 2025-11-08 13:16:24.192296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4475c1ce824d'
down_revision: Union[str, Sequence[str], None] = '08a9ea3e07c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recargasaldo', sa.Column('bonus_cashback_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recargasaldo', 'bonus_cashback_percent')
    # ### end Alembic commands ###
