"""adiciona instrucoes especificas ao estoque

Revision ID: 4d237e3b5ee6
Revises: 321a7ab448cc
Create Date: 2025-11-28 10:38:45.946012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d237e3b5ee6'
down_revision: Union[str, Sequence[str], None] = '321a7ab448cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoqueconta', sa.Column('instrucoes_especificas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoqueconta', 'instrucoes_especificas')
    # ### end Alembic commands ###
