"""adiciona instrucoes pos compra ao produto

Revision ID: 8795a348eabe
Revises: cac9c4bf51de
Create Date: 2025-11-05 21:44:17.723339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8795a348eabe'
down_revision: Union[str, Sequence[str], None] = 'cac9c4bf51de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('instrucoes_pos_compra', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'instrucoes_pos_compra')
    # ### end Alembic commands ###
