"""adiciona_data_expiracao_ao_estoque

Revision ID: bf72222b27c8
Revises: 4475c1ce824d
Create Date: 2025-11-11 16:41:28.142397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf72222b27c8'
down_revision: Union[str, Sequence[str], None] = '4475c1ce824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoqueconta', sa.Column('data_expiracao', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoqueconta', 'data_expiracao')
    # ### end Alembic commands ###
