"""Cria tabelas iniciais do projeto

Revision ID: eb4a1913898b
Revises: 
Create Date: 2025-10-30 14:44:00.379463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb4a1913898b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_nome'), 'produto', ['nome'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saldo_carteira', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_telegram_id'), 'usuario', ['telegram_id'], unique=True)
    op.create_table('estoqueconta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_slots', sa.Integer(), nullable=False),
    sa.Column('slots_ocupados', sa.Integer(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('requer_atencao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giftcard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_utilizado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('utilizado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por_admin_id', sa.Uuid(), nullable=False),
    sa.Column('utilizado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_admin_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['utilizado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_giftcard_codigo'), 'giftcard', ['codigo'], unique=True)
    op.create_table('recargasaldo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valor_solicitado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_pagamento', sa.Enum('PENDENTE', 'PAGO', 'FALHOU', 'ESTORNADO', name='tipostatuspagamento'), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pix_copia_e_cola', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recargasaldo_gateway_id'), 'recargasaldo', ['gateway_id'], unique=False)
    op.create_table('sugestaostreaming',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome_streaming', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sugestaostreaming_nome_streaming'), 'sugestaostreaming', ['nome_streaming'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('estoque_conta_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_conta_id'], ['estoqueconta.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticketsuporte',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('motivo', sa.Enum('LOGIN_INVALIDO', 'SEM_ASSINATURA', 'CONTA_CAIU', 'OUTRO', name='tipomotivoticket'), nullable=False),
    sa.Column('descricao_outros', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANALISE', 'RESOLVIDO', 'FECHADO', name='tipostatusticket'), nullable=False),
    sa.Column('resolucao', sa.Enum('NA', 'CONTA_TROCADA', 'REEMBOLSO_CARTEIRA', 'MANUAL', name='tiporesolucaoticket'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('estoque_conta_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_conta_id'], ['estoqueconta.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_ticketsuporte_status'), 'ticketsuporte', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketsuporte_status'), table_name='ticketsuporte')
    op.drop_table('ticketsuporte')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_sugestaostreaming_nome_streaming'), table_name='sugestaostreaming')
    op.drop_table('sugestaostreaming')
    op.drop_index(op.f('ix_recargasaldo_gateway_id'), table_name='recargasaldo')
    op.drop_table('recargasaldo')
    op.drop_index(op.f('ix_giftcard_codigo'), table_name='giftcard')
    op.drop_table('giftcard')
    op.drop_table('estoqueconta')
    op.drop_index(op.f('ix_usuario_telegram_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_produto_nome'), table_name='produto')
    op.drop_table('produto')
    # ### end Alembic commands ###
