"""adiciona requer_email_cliente ao produto

Revision ID: fa1531501166
Revises: 23892b69acd1
Create Date: 2025-11-03 18:19:56.050744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1531501166'
down_revision: Union[str, Sequence[str], None] = '23892b69acd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('requer_email_cliente', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'requer_email_cliente')
    # ### end Alembic commands ###
